### PR TITLE
Support multiple window for runner-panes

### PR DESCRIPTION
**Pull request by Yuki-Inoue**
Runner pane gets associated with each tmux window, rather than treated
globally.

### CODE REVIEW

**Comment by Yuki-Inoue** [comment]
Wait, I noticed the entry for runner panes manually closed would remain forever...  Closing until I finish that fix.

**Comment by Yuki-Inoue** [comment]
@syohex By the way, is it OK to use `dash`? That removing entries for unexisting windows would require list manipulation, and I though it would be easier if I could use the list library.

**Comment by syohex** [comment]
I don't like to add dependencies as possible.

**Comment by Yuki-Inoue** [comment]
OK, I understand.

**Pull request closed without merging**
